"""Canonical metrics schema for run-level and aggregate study outputs."""

RUN_METRICS_FIELDS = [
    "run_name",
    "config_name",
    "baseline_name",
    "dataset_name",
    "dataset_train_examples",
    "dataset_eval_examples",
    "seed",
    "architecture_type",
    "model_name",
    "final_train_loss",
    "final_eval_loss",
    "best_eval_loss",
    "eval_perplexity",
    "stage_2_token_accuracy",
    "stage_3_token_accuracy",
    "final_answer_accuracy",
    "final_answer_exact_match",
    "normalized_numeric_answer_accuracy",
    "wall_time_seconds_total",
    "wall_time_seconds_train",
    "wall_time_seconds_eval",
    "tokens_seen_train",
    "tokens_seen_eval",
    "tokens_per_second_train",
    "tokens_per_second_eval",
    "steps_per_second",
    "seconds_per_step",
    "trainable_params",
    "total_params",
    "trainable_param_fraction",
    "recurrence_steps",
    "effective_forward_passes_per_example",
    "global_steps_completed",
    "epochs_completed",
    "backend",
    "latent_cache",
]

AGG_GROUP_BY_FIELDS = ["baseline_name", "architecture_type", "model_name", "dataset_name", "config_name"]
AGGREGATE_METRICS = [
    "final_eval_loss",
    "eval_perplexity",
    "final_answer_accuracy",
    "final_answer_exact_match",
    "normalized_numeric_answer_accuracy",
    "wall_time_seconds_total",
    "tokens_per_second_train",
    "trainable_param_fraction",
]
